services:
   todo_express_db:
    container_name: todo_express_db
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432